import { Command } from "../types/commands";
import { ActivateCardCommand } from "./ActivateCardCommand";
import { BanishCommand } from "./BanishCommand";
import { ChangeCardAtkDefCommand } from "./ChangeCardAtkDefCommand";
import { ChangeCardPositionCommand } from "./ChangeCardPositionCommand";
import { DestroyCardCommand } from "./DestroyCard";
import { DrawFromDeckCommand } from "./DrawFromDeckCommand";
import { FieldSpellCommand } from "./FieldSpellCommand";
import { FlipCommand } from "./FlipCommand";
import { FusionSummonCommand } from "./FusionSummonCommand";
import { LinkSummonCommand } from "./LinkSummonCommand";
import { MillFromDeckCommand } from "./MillFromDeckCommand";
import { MoveCardCommand } from "./MoveCardCommand";
import { NormalSummonCommand } from "./NormalSummonCommand";
import { RevealCommand } from "./RevealCommand";
import { SendCardToGYCommand } from "./SendCardToGY";
import { SetCardCommand } from "./SetCardCommand";
import { SetMonsterCommand } from "./SetMonsterCommand";
import { ShuffleDeckCommand } from "./ShuffleDeck";
import { SpecialSummonCommand } from "./SpecialSummonCommand";
import { SynchroSummonCommand } from "./SynchroSummonCommand";
import { ToDeckCommand } from "./ToDeckCommand";
import { ToExtraDeckCommand } from "./ToExtraDeckCommand";
import { ToHandCommand } from "./ToHandCommand";
import { ToSTCommand } from "./ToSTCommand";
import { TributeSetCommand } from "./TributeSetCommand";
import { TributeSummonCommand } from "./TributeSummonCommand";
import { XYZAttachMaterialCommand } from "./XYZAttachMaterialCommand";
import { XYZDetachMaterialCommand } from "./XYZDetachMaterialCommand";
import { XYZSummonCommand } from "./XYZSummonCommand";
export declare const Commands: {
    NormalSummonCommand: typeof NormalSummonCommand;
    SetMonsterCommand: typeof SetMonsterCommand;
    SetCardCommand: typeof SetCardCommand;
    SendCardToGYCommand: typeof SendCardToGYCommand;
    BanishCommand: typeof BanishCommand;
    DrawFromDeckCommand: typeof DrawFromDeckCommand;
    MillFromDeckCommand: typeof MillFromDeckCommand;
    ActivateCardCommand: typeof ActivateCardCommand;
    SpecialSummonCommand: typeof SpecialSummonCommand;
    TributeSummonCommand: typeof TributeSummonCommand;
    TributeSetCommand: typeof TributeSetCommand;
    LinkSummonCommand: typeof LinkSummonCommand;
    FusionSummonCommand: typeof FusionSummonCommand;
    SynchroSummonCommand: typeof SynchroSummonCommand;
    XYZSummonCommand: typeof XYZSummonCommand;
    XYZAttachMaterialCommand: typeof XYZAttachMaterialCommand;
    XYZDetachMaterialCommand: typeof XYZDetachMaterialCommand;
    ToDeckCommand: typeof ToDeckCommand;
    ShuffleDeckCommand: typeof ShuffleDeckCommand;
    DestroyCardCommand: typeof DestroyCardCommand;
    RevealCommand: typeof RevealCommand;
    ToExtraDeckCommand: typeof ToExtraDeckCommand;
    ToHandCommand: typeof ToHandCommand;
    FieldSpellCommand: typeof FieldSpellCommand;
    ChangeCardPositionCommand: typeof ChangeCardPositionCommand;
    ChangeCardAtkDefCommand: typeof ChangeCardAtkDefCommand;
    FlipCommand: typeof FlipCommand;
    ToSTCommand: typeof ToSTCommand;
    MoveCardCommand: typeof MoveCardCommand;
};
export declare const COMMANDS_BY_NAME: any;
export declare function GetCommandByClassName<T = Command>(commandClassName: string): T | null;
