export * from './game/YGOCore';
export * from './game/YGODuelLog';
export * from './game/YGOGameUtils';
export * from './types/duel-events';
export declare const YGOCommands: {
    NormalSummonCommand: typeof import("./commands").NormalSummonCommand;
    SetMonsterCommand: typeof import("./commands").SetMonsterCommand;
    SetCardCommand: typeof import("./commands").SetCardCommand;
    SendCardToGYCommand: typeof import("./commands").SendCardToGYCommand;
    BanishCommand: typeof import("./commands").BanishCommand;
    DrawFromDeckCommand: typeof import("./commands").DrawFromDeckCommand;
    MillFromDeckCommand: typeof import("./commands").MillFromDeckCommand;
    ActivateCardCommand: typeof import("./commands").ActivateCardCommand;
    SpecialSummonCommand: typeof import("./commands").SpecialSummonCommand;
    TributeSummonCommand: typeof import("./commands").TributeSummonCommand;
    TributeSetCommand: typeof import("./commands").TributeSetCommand;
    LinkSummonCommand: typeof import("./commands").LinkSummonCommand;
    XYZSummonCommand: typeof import("./commands").XYZSummonCommand;
    XYZAttachMaterialCommand: typeof import("./commands").XYZAttachMaterialCommand;
    XYZDetachMaterialCommand: typeof import("./commands").XYZDetachMaterialCommand;
    ToDeckCommand: typeof import("./commands").ToDeckCommand;
    ShuffleDeckCommand: typeof import("./commands").ShuffleDeckCommand;
    DestroyCardCommand: typeof import("./commands").DestroyCardCommand;
    RevealCommand: typeof import("./commands").RevealCommand;
    ToExtraDeckCommand: typeof import("./commands").ToExtraDeckCommand;
    ToHandCommand: typeof import("./commands").ToHandCommand;
};
