# Stage 1: Generate SSL certificates
FROM node:22-alpine

WORKDIR /app

COPY __tests__/package.json ./
COPY __tests__/src/network/bootstrap-node.js ./src/bootstrap-node.js

# Install dependencies
RUN npm install --frozen-lockfile

CMD ["npm", "run", "bootstrap-node"]