import { Command } from "../types/commands";
import { PlayerField, YGOCoreEvents, YGOPhase, YGOProps } from "../types/types";
import { EventBus } from "../utils/event-bus";
import { YGODuelLog } from "./YGODuelLog";
import { YGOGameState } from "./YGOGameState";
export declare class YGOCore {
    private commandId;
    currentPlayer: number;
    phase: YGOPhase;
    props: YGOProps;
    state: YGOGameState;
    commands: Command[];
    commandIndex: number;
    duelLog: YGODuelLog;
    events: EventBus<YGOCoreEvents>;
    constructor(props: YGOProps);
    start(): void;
    setCurrentPlayer(player: number): void;
    exec(command: Command): Command;
    peek(): Command | null;
    redo(): Command | null;
    undo(): Command | null;
    goToCommand(command: Command): boolean;
    hasNextCommand(): boolean;
    hasPrevCommand(): boolean;
    getNextCommandId(): number;
    getReplayData(): import("../types/types").YGOReplayData;
    getField(player: number): PlayerField;
    private createYGOCommands;
}
